Завдання 1: Створення матриць та векторів
Створіть numpy вектор vector розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:

Генерація випадкових чисел з модулем random.uniform.

Створення вектора з допомогою метода numpy np.random.rand

Створіть матрицю matrix типу numpy.array розмірності 3x3 з наступними значеннями

matrix=⎡⎣⎢112029142332172635⎤⎦⎥ 

будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.

In [3]:
import numpy as np
import random

vector = np.array([random.uniform(0, 1) for _ in range(10)])
vector = np.random.rand(10)
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("Вектор:", vector)
print("Розмір вектора:", vector.shape)
print("Матриця:", matrix)
print("Розмір матриці:", matrix.shape)

Вектор: [0.54611378 0.88096408 0.82829925 0.91777907 0.47016492 0.49289209
 0.91422501 0.38949506 0.08141172 0.06599188]
Розмір вектора: (10,)
Матриця: [[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)


Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:

Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
Створіть новий вектор, який містить квадрат кожного vector без циклів.

In [5]:
vector_plus10 = np.round(vector + 10, 2)
print("Вектор + 10 (округлено):", vector_plus10)

matrix_times2 = matrix * 2
print("Матриця * 2:", matrix_times2)

vector_squared = vector ** 2
print("Квадрат кожного елемента вектора:", vector_squared)

Вектор + 10 (округлено): [10.55 10.88 10.83 10.92 10.47 10.49 10.91 10.39 10.08 10.07]
Матриця * 2: [[22 28 34]
 [40 46 52]
 [58 64 70]]
Квадрат кожного елемента вектора: [0.29824026 0.77609771 0.68607964 0.84231843 0.22105505 0.24294261
 0.83580736 0.1517064  0.00662787 0.00435493]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

B = np.array([[7,  8,  9],
              [10, 11, 12]])

result_matrix = B @ A
print("result_matrix (2x2):", result_matrix)

C = np.array([[1],
              [2]])

result_C = result_matrix @ C
print("result_matrix @ C (2x1):", result_C)

D = np.array([[1, 0],
              [0, 1]])  # одинична матриця для прикладу

result_D = result_matrix @ D
print("result_matrix @ D (2x2):", result_D)

result_matrix (2x2): [[ 76 100]
 [103 136]]
result_matrix @ C (2x1): [[276]
 [375]]
result_matrix @ D (2x2): [[ 76 100]
 [103 136]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [12]:


#1
print("result_matrix.T:", result_matrix.T)
#2
print("vector.shape:", vector.shape)
print("vector.T.shape:", vector.T.shape)
#3
column_vector = np.expand_dims(vector, axis=1)
print("column_vector:", column_vector)
print("column_vector.shape:", column_vector.shape)  # (10, 1)
#4
print("column_vector.T:", column_vector.T)
print("column_vector.T.shape:", column_vector.T.shape)  # (1, 10)

result_matrix.T: [[ 76 103]
 [100 136]]
vector.shape: (10,)
vector.T.shape: (10,)
column_vector: [[0.54611378]
 [0.88096408]
 [0.82829925]
 [0.91777907]
 [0.47016492]
 [0.49289209]
 [0.91422501]
 [0.38949506]
 [0.08141172]
 [0.06599188]]
column_vector.shape: (10, 1)
column_vector.T: [[0.54611378 0.88096408 0.82829925 0.91777907 0.47016492 0.49289209
  0.91422501 0.38949506 0.08141172 0.06599188]]
column_vector.T.shape: (1, 10)
