In [2]:
import pandas as pd
import numpy as np

In [24]:
x = np.array([5, 15, 25, 35, 45])
zeros = np.zeros ((7))
ones = np.ones ((6))
numbers = np.arange(10,20)
print (x)
print(zeros)
print (ones)
print (numbers)

[ 5 15 25 35 45]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[10 11 12 13 14 15 16 17 18 19]


In [9]:
number=np.array([12,24,36,48,60])
print (number *2)
print (number +10)
print (number **2)
print (np.sqrt (number))

[ 24  48  72  96 120]
[22 34 46 58 70]
[ 144  576 1296 2304 3600]
[3.46410162 4.89897949 6.         6.92820323 7.74596669]


In [12]:
data=np.array([18,27,33,41,52,68,79])
print (np.mean(data))
print (np.min(data))
print (np.max(data))
print (np.sum(data))

45.42857142857143
18
79
318


In [23]:
arr=np.array([15,22,35,44,58,67])
print (arr[0])
print (arr[-1])
print (arr[1:3])
print (arr[arr>40])

15
67
[22 35]
[44 58 67]


In [32]:
matrix=np.array( [[2,4,6],
                 [8,10,12],
                 [14,16,18]])
print(matrix.shape)
print(matrix[0])
print(matrix[:,1])

(3, 3)
[2 4 6]
[ 4 10 16]
